(Arrays)=
### Arrays

En array er en måte å lagre data på. Arrays likner på {ref}`Lister`, men har flere viktige forskjeller.

For å bruke arrays må vi bruke en pakke. Vi bruker pakken `numpy`. Mange Python-installasjoner vil inkludere denne pakken, men man kan også installere pakken ved å skrive `pip install numpy` i terminalvinduet.

Når vi har `numpy`-pakken kan vi lage en array.

In [2]:
import numpy as np

array = np.array([1, 2, 3])

print(array)

[1 2 3]


Arrays kan bare ha elementer med data av samme type.

In [5]:
import numpy as np

array = np.array([1, "Alfa", True])
array2 = np.array([1, 2, 3.14])

print(array)
print(array2)

['1' 'Alfa' 'True']
[1.   2.   3.14]


Her ser vi at alle elementene i `array` har blitt gjort om til tekststrenger, og at alle elementene i `array2` har blitt gjort om til flyttall.

En annen vesentlig forskjell er at det går mye raskere å finne elementer i arrays enn i lister, men det tar mye lengre tid å legge til og trekke ut elementer fra en array.

#### Vektorregning

Arrays er vektorer. Det gjør at vi kan bruke de til vektorregning.

In [14]:
import numpy as np

l1 = [1, 1] # Liste 1
l2 = [1, 1] # Liste 2

a1 = np.array(l1) # Lager array av liste 1
a2 = np.array(l2) # Lager array av liste 2

print(l1 + l2) # Legger sammen lister
print(a1 + a2) # Legger sammen arrays

[1, 1, 1, 1]
[2 2]


Legger vi sammen lister, så settes de sammen til en ny større liste. Altså blir `[1, 1] + [1, 1] = [1, 1, 1, 1]`. Legger vi sammen arrays så fungerer det på samme måte som i vektorregningen. Altså at $[1, 1] + [1, 1] = [1+1, 1+1] = [2, 2]$

#### `arange()`-funksjonen

Vi ønsker noen gang å lage arrays med tall i stigende rekkefølge. Det kan vi gjøre med `arange()`-funksjonen.

In [13]:
import numpy as np

print(np.arange(10))        # Alle tall fra og med 0 til 10
print(np.arange(1, 10))     # Alle tall fra og med 1 til 10
print(np.arange(0, 10, 2))  # Alle tall fra og med 0 til 10, men med steglengde 2

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


#### `zeros()`-funksjonen

Hvis vi ønsker å lage mange nuller så kan vi bruke `zeros()`-funksjonen. Legger vi en tuppel (f.eks `(3, 3)`) inn som parameter, så får vi en todimensjonell array.

In [22]:
import numpy as np

print(np.zeros(5))      # Lager en array med 5 nuller
print(np.zeros((3,3)))  # Lager en 5x5 array med nuller

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Finne elementer (indeksere)

Vi kan indeksere og arrays på denne måten. Dette fungerer på samme måte som for lister både i én og to dimensjoner.

In [52]:
import numpy as np

# 1 dimensjon
arr = np.array([1, 2, 3])
print(arr[0])

# 2 dimensjoner
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
print(arr2[0][1])

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


#### Legge til og trekke fra verdier

Vi kan legge til elementer ved å bruke `numpy.append()`-funksjonen. Merk at denne fungerer veldig annerledes fra den vanlige `append()`-metoden for lister.

Vi kan trekke fra elementer ved å bruke `numpy.delete()`-funksjonen. Merk at denne fungerer veldig annerledes fra den vanlige `pop()`-metoden for lister.

In [53]:
import numpy as np

arr = np.array([1, 2, 3])   # Lager et array som kalles arr
arr = np.append(arr, 4)     # Legger til elementet 4 på slutten av listen
arr = np.delete(arr, 0)     # Fjerner elementet ved indeksen 0
print(arr)

[2 3 4]
