(Arrays)=
### Arrays

En array er en måte å lagre data på. Arrays likner på {ref}`Lister`, men har flere viktige forskjeller.

For å bruke arrays må vi bruke en pakke som heter `numpy`. Mange Python-installasjoner vil inkludere denne pakken, men man kan også installere pakken ved å skrive `pip install numpy` i terminalvinduet.

Når vi har `numpy`-pakken kan vi lage en array.

In [2]:
import numpy as np

array = np.array([1, 2, 3])

print(array)

[1 2 3]


Arrays kan bare ha elementer med data av samme type. Hvis man legger inn flere typer data vil alle blir gjort om til samme datatype.

In [5]:
import numpy as np

array = np.array([1, "Alfa", True])
array2 = np.array([1, 2, 3.14])

print(array)
print(array2)

['1' 'Alfa' 'True']
[1.   2.   3.14]


Her ser vi at alle elementene i `array` har blitt gjort om til tekststrenger, og at alle elementene i `array2` har blitt gjort om til flyttall. Dette kalles *upcasting*. Vi trenger ikke tenke på dette om vi bare jobber med samme type elementer i et array.

#### Vektorregning

Arrays er vektorer. Det gjør at vi kan bruke de til vektorregning.

In [14]:
import numpy as np

l1 = [1, 1] # Liste 1
l2 = [1, 1] # Liste 2

a1 = np.array(l1) # Lager array av liste 1
a2 = np.array(l2) # Lager array av liste 2

print(l1 + l2) # Legger sammen lister
print(a1 + a2) # Legger sammen arrays

[1, 1, 1, 1]
[2 2]


Legger vi sammen lister, så settes de sammen til en ny større liste. Altså blir `[1, 1] + [1, 1] = [1, 1, 1, 1]`. 

Legger vi sammen arrays så fungerer det på samme måte som i vektorregningen. Altså at $[1, 1] + [1, 1] = [1+1, 1+1] = [2, 2]$

#### `arange()`-funksjonen

For å lage arrays med tall i stigende rekkefølge kan vi bruke `arange()`-funksjonen.

In [13]:
import numpy as np

print(np.arange(10))        # Alle tall fra og med 0 til 10
print(np.arange(1, 10))     # Alle tall fra og med 1 til 10
print(np.arange(0, 10, 2))  # Alle tall fra og med 0 til 10, men med steglengde 2

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


På samme måte som i `range()`-funksjonen er slutten i `arange()`-funksjonen ikke inkluderende. Det vil si at den bare går *til* sluttverdien, ikke *til og med*.

#### `linspace()`-funksjonen og matematiske funksjoner

For å lage en jevn fordeling av tall i et intervall kan vi bruke `linspace()`-funksjonen. Denne er veldig nyttig til plotting.

In [261]:
import numpy as np

print(np.linspace(0, 2, 5)) # 5 tall mellom 0 og 2 (inkluderende)
print(np.linspace(-5, 5, 10)) # 10 tall mellom -5 og 5 (inkluderende)

[0.  0.5 1.  1.5 2. ]
[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


Dette er veldig nyttig når vi skal lage `x`-verdier for matematiske funksjoner.

In [262]:
import numpy as np

def f(x):
    return x**2

x = np.linspace(-2, 2, 5) # 50 tall mellom -5 og 5
y = f(x)

print("x-verdier:", x)
print("y-verdier (x**2):", y)

x-verdier: [-2. -1.  0.  1.  2.]
y-verdier (x**2): [4. 1. 0. 1. 4.]


#### `concatenate()`-funksjonen

Hvis vi ønsker å legge sammen arrays til nye større arrays kan vi bruke `concatenate()`-funksjonen.

In [263]:
import numpy as np

arr1 = np.arange(1, 4)
arr2 = np.arange(1, 4)

print(np.concatenate((arr1, arr2)))

[1 2 3 1 2 3]


#### `zeros()`-funksjonen

Hvis vi ønsker å fylle en array med mange nuller så kan vi bruke `zeros()`-funksjonen. Legger vi en tuppel (f.eks `(3, 3)`) inn som parameter, så får vi en todimensjonell array.

In [266]:
import numpy as np

print(np.zeros(5)) # Lager en array med 5 nuller
print(np.zeros((3,3))) # Lager en 5x5 array med nuller

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Det finnes også en funksjon som heter `ones()`. Kanskje du klarer å tenke deg frem til hva den gjør?

#### `sort()`-funksjonen

For å få en sortert array (stigende) kan vi bruke `sort()`-funksjonen.

In [264]:
import numpy as np
from random import randint

arr = np.zeros(10) # Lager et array med nuller.

for n in range(len(arr)):
    arr[n] = randint(1, 10) # Setter hvert element til en tilfeldig verdi.

print("Array:", arr) # Skriver ut arrayet.
print("Sortert array:", np.sort(arr)) # Skriver ut det sorterte arrayet.

Array: [ 7.  7.  4. 10. 10.  6.  2.  8.  9. 10.]
Sortert array: [ 2.  4.  6.  7.  7.  8.  9. 10. 10. 10.]


#### `flip()`-funksjonen

For å få en reversert array kan vi bruke `flip()`-funksjonen.

In [265]:
import numpy as np

arr = np.arange(1, 10)

print("Array:", arr)
print("Reversert array:", np.flip(arr))

Array: [1 2 3 4 5 6 7 8 9]
Reversert array: [9 8 7 6 5 4 3 2 1]


#### `reshape()`-funksjonen

Hvis vi ønsker å gjøre endre på formen til en array kan vi bruke `reshape()`-funksjonen.

In [267]:
import numpy as np

arr = np.arange(1,10) # Lager en array med tallene fra og med en til 10.

print("Array:", arr)
print("Omformet (3, 3):")
print(np.reshape(arr, (3, 3))) # Omformer arrayet til (3, 3). 3 rader og 3 kolonner.

Array: [1 2 3 4 5 6 7 8 9]
Omformet (3, 3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Finne elementer (indeksere)

Vi kan indeksere og arrays på denne måten. Dette fungerer på samme måte som for lister både i én og to dimensjoner.

In [268]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr[0]) # Skriver ut første element i listen

1


Vi kan indeksere 2d-arrays på denne måten.

In [269]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr) # Hele arrayen
print("Element i posisjon [0][0]: ", arr[0][0]) # Skriver elementet i første rad og første kolonne
print("Element i posisjon [1][1]: ", arr[1][1]) # Skriver elementet i andre rad og andre kolonne

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element i posisjon [0][0]:  1
Element i posisjon [1][1]:  5


#### `shape()`-funksjonen

Vi ønsker noen ganger å se hvilken form en array har. Til det kan vi bruke `shape()`-funksjonen.

In [270]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.shape(arr))

(2, 3)


Vi ser at formen på arrayet er 2x3. To rader og tre kolonner.

#### Legge til og trekke fra elementer

Vi kan legge til elementer i arrays ved å bruke `append()`-funksjonen.

In [271]:
import numpy as np

arr = np.array([1, 2, 3]) # Lager et array som kalles arr

print(arr)

arr = np.append(arr, 4)   # Legger til elementet 4 på slutten av arrayet

print(arr)

[1 2 3]
[1 2 3 4]


Vi kan trekke fra elementer i arrays ved å bruke `delete()`-funksjonen.

In [272]:
import numpy as np

arr = np.array([1, 2, 3]) # Lager et array som kalles arr

print(arr)

arr = np.delete(arr, 0)   # Fjerner elementet med indeks 0

print(arr)

[1 2 3]
[2 3]


Vi ser at `np.append()` og `np.delete()` fungerer annerledes enn `append()`- og `pop()`-metodene i Python. 

`append()`- og `pop()` legger til eller fjerner elementer i en liste. 

`np.append()` og `np.delete()` returnerer en ny array. Enten med et nytt element, eller med et element fjernet.

---

#### Oppgaver

##### Oppgave 1

I denne oppgaven skal du lage flere arrays.

1. Skriv ut en array som inneholder alle oddetallene fra og med 1 til og med 19.
2. Skriv ut en array som inneholder alle oddetallene fra og med 1 til og med 19, baklengs.
3. Skriv ut en 2d-array med dimensjonene (5, 5) og som er fylt med nuller.
4. Skriv ut en 2d-array med dimensjonene (5, 5) og som er fylt med enere.


#### Oppgave 2

Lag en array med lengde 9 fylt med tilfeldige tall mellom 1 og 10 (inkluderende).

1. Skriv ut arrayet.
2. Skriv ut arrayet, sortert.
3. Skriv ut det sorterte arrayet, omformet til (3, 3).

#### Oppgave 3

Lag en array med navn `x` fylt med 9 verdier jevnt fordelt mellom -2 og 2.

1. Lag en funksjon `f(x)` som tar en `x` som parameter og returnerer `abs(x)`.
2. Lag en array `y` ved å sette inn arrayet `x` i funksjonen `f(x)`.
3. Skriv ut både `x` og `y`.

Se på utskriften av `x` og `y`. Hva gjør `abs()`-funksjonen?

##### Oppgave 4

Skriv ut gangetabellen med alle tallene fra og med `1` til og med `10` ved å lage en todimensjonell array.

En mulig utskrift kan se slik ut:

```
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
```

> Hint: Det kan være lurt å starte med å lage en array som `np.zeros((10, 10)).astype(int)`. `.astype()`-metoden endrer arrayet slik at det i utgangspunktet blir fylt med heltall, ikke flyttall. Deretter må vi lage løkker for å indeksere og sette elementer i arrayet.

Bonus: Modifiser programmet slik at man kan skrive inn dimensjonene for gangetabellen